language: php

cache:
  directories:
    - $HOME/.composer/cache

services:
  - mongodb

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: MONGO_VERSION=stable
    - php: 5.6
      env: DEPENDENCIES='low' MONGO_VERSION=stable
    - php: 7.0
      env: ADAPTER_VERSION="^1.0.0" MONGODB_VERSION=stable
    - php: 7.1
      env: ADAPTER_VERSION="^1.0.0" MONGODB_VERSION=stable
    - php: 7.2
      env: ADAPTER_VERSION="^1.0.0" MONGODB_VERSION=stable
    - php: 7.3
      env: ADAPTER_VERSION="^1.0.0" MONGODB_VERSION=stable

before_install:
  - phpenv config-add .travis-config.ini || return 0
  - composer self-update

install:
  - if [ "x${MONGO_VERSION}" != "x" ]; then yes '' | pecl -q install -f mongo-${MONGO_VERSION} && echo "extension=mongo.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`; fi
  - if [ "x${MONGODB_VERSION}" != "x" ]; then pecl install -f mongodb-${MONGODB_VERSION}; fi
  - if [ "x${ADAPTER_VERSION}" != "x" ]; then composer config "platform.ext-mongo" "1.6.16" && composer require "alcaeus/mongo-php-adapter=${ADAPTER_VERSION}"; fi
  - if [ "$DEPENDENCIES" != "low" ]; then composer update --prefer-dist --no-scripts --no-interaction; fi;
  - if [ "$DEPENDENCIES" == "low" ]; then composer update --prefer-lowest --no-scripts --no-interaction; fi;

script:
  - ./vendor/bin/grumphp run
