language: php
php:
  - 5.5
  - 5.4
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - phpenv config-add .travis-config.ini
  - composer self-update
  - pecl install -f mongo-1.4.1
  - composer install --dev --prefer-source

# Add PSR-4 support when https://github.com/fabpot/PHP-CS-Fixer/issues/311 is solved
script:
  - ./vendor/bin/php-cs-fixer fix . --dry-run  --fixers=-psr0
  - ./vendor/bin/phpunit

services:
  - mongodb